spring:
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true // sout으로 찍기때문에 log를 사용하는 org.hibernate.SQL: debug 를 사용하자
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace